using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Carallon.MLibrary.Fixture.Enums
{
    public enum FeatureName
    {
        No_Feature,
        Null,
        Intensity,
        Position,
        Colour,
        BeamContent,
        BeamShape,
        MediaServerIntensity,
        MediaServerColour,
        MediaServerContent,
        MediaServerAudio,
        Projector,
        Camera,
        Control,
        Effects,
        Tilt,
        Pan,
        Gobo_Wheel,
        Effect_Wheel,
        Gobo_Index_Rotate,
        Wheel_Spin,
        Gobo_Index,
        Gobo_Rotate,
        Strobe,
        Iris,
        Colour_Wheel_Select,
        Effect_Wheel_Select,
        Shutter,
        Gobo_Wheel_Select,
        Cyan,
        Yellow,
        Magenta,
        Frost,
        Fixture_Global_Reset,
        Position_MSpeed_Track,
        Position_MSpeed,
        Position_Reset,
        Lamp_Off,
        Shutter_Reset,
        Iris_Reset,
        Zoom_Reset,
        Focus_Reset,
        Gobo_Wheel_Reset,
        Gobo_Reset,
        Effect_Wheel_Reset,
        Effect_Reset,
        Colour_Wheel_Reset,
        Colour_Mix_Reset,
        CTO_Reset,
        Shutter_Strobe,
        Strobe_Pulse_Close,
        Strobe_Pulse_Open,
        Strobe_Random,
        Iris_Strobe_Pulse,
        Iris_Strobe_Pulse_Close,
        Unknown,
        Gobo_Wheel_Spin,
        Effect_Index,
        Effect_Rotate,
        Effect_Wheel_Select_Blink,
        Colour_Wheel_Select_Blink,
        Position_Blink,
        Strobe_Mechanical_Electronic,
        Gobo_Wheel_Mode_Continuous,
        Effect_Wheel_Mode_Continuous,
        Effect_Wheel_Mode_Whole_Effects,
        Gobo_Wheel_Mode_Whole_Gobos,
        Lamp_Power_Mode_Manual,
        Lamp_Power_Mode_Auto,
        Lamp_On,
        Lamp_Power,
        Zoom,
        Blue,
        Green,
        Amber,
        Red,
        White,
        Connected_Load,
        Cool_White,
        Warm_White,
        Animation_Wheel_Select,
        Animation_Wheel_Incline,


    }
}
